### ISSUE TITLE
Unable to discover any upnp device in a network.

### ISSUE THREAD

**Issue by sanket-mindstix** [diversario/node-ssdp#28]
I am executing this module on my widows machine and module is failing to get result where as same module is working on Ubuntu i.e returning upnp devices info in a network.

**Comment by oeuillot** [comment]
[Silly question] Have you authorized your firewall to open/listen the upnp port (1900) ?

**Comment by sanket-mindstix** [comment]
I have disabled my firewall settings and tried but not getting results.

**Comment by oeuillot** [comment]
Can you add these parameters to the command line:
--ssdpLog --ssdpLogLevel debug 
Can you post your logs ?

**Comment by sanket-mindstix** [comment]
I am facing same issue on raspberry pi device. Could you please check, unable to get upnp devices in a network. I am using upnp client module. Thanks.

**Comment by smolleyes** [comment]
hi

same thing on all windows os, no problems on osX or linux... the search message seems not broadcasted or don t but if i shutdown my upnp device then restart it i have my device showing.. strange

thanks

**Comment by smolleyes** [comment]
REALLLLYY need a fix on this, very very problematic !!!

**Comment by diversario** [comment]
@smolleyes I need to first get a Windows machine to test this but in the mean time – is your issue related to #25, specifically https://github.com/diversario/node-ssdp/issues/25#issuecomment-58663815 ? Could you modify your local `node-ssdp` code to add the suggested bit and see if it helps?

**Comment by diversario** [comment]
Please update to v2.2.1 and see if this is resolved.
