### ISSUE TITLE
require('./lib-cov/server'), etc... on index.js

### ISSUE THREAD

**Issue by getmeaway** [diversario/node-ssdp#35]
On *index.js* there are 3 ```require('./lib-cov/*') ``` but **lib-cov** folder is not present in the source code.
Is it sufficient to copy **lib** folder (and all his content) as **lib-cov** or modify the index.js to include directly the 3 lib files?

**Comment by diversario** [comment]
`lib-cov` is an instrumented copy of the module used for tests to get coverage; it's created when running `make coverage` and removed after tests are done.

Are you having some issue related to that `require` call?

**Comment by getmeaway** [comment]
i have issues on ```require``` only when using **enclosejs** to incapsulate my app into a binary file. 
[EncloseJs](https://www.npmjs.com/package/enclose) can not resolve dependencies on runtime so on the lines 2, 3 and 4 of *index.js*, it tries to include both **lib/*.js** and **lib-cov/\*.js**. 
I know my problem it's not because of node-ssdp, so i think if i require directly 'lib' files (by modifying lines 2,3,4), everything goes fine

**Comment by diversario** [comment]
Oh, interesting, I didn't know you could do that with node apps!
Yeah, I think if EncloseJS tries to require everything unconditionally then you just need to modify the `index.js` file to not even try to use `lib-cov`.

**Comment by getmeaway** [comment]
yes this way it works fine, but modifying a dependency is not a good practice, maybe i'm going to fork node-ssdp ;)

**Comment by diversario** [comment]
I understand. Let me look into it, maybe I'll find a good way to avoid this issue. I think I can just modify `index.js` to define the path first and they calling `require` just once.

**Comment by diversario** [comment]
Can you see if https://github.com/diversario/node-ssdp/tree/fix/i35-avoid-extra-require fixes your issue?

**Comment by getmeaway** [comment]
Great! this works fine and in a clean way! 

The problem was because EncloseJS search all the require statements into the project (dependencies too) and tries to include all the module it finds. 
When it can not find a module it stops reporting an error (as in the case of *lib-cov*). 
With this fix, to run enclose and get a binary file, it is sufficient to include the path to *lib* folder into a config file 

Thanks a lot!

**Comment by diversario** [comment]
Glad it worked! I'll publish a new version when I get to my computer, hopefully in ~12 hours.

**Comment by No9** [comment]
Will test on browserify as I had to work around on that environment too
