### ISSUE TITLE
Extra advert?

### ISSUE THREAD

**Issue by achingbrain** [diversario/node-ssdp#36]
When I start a `node-ssdp` server and log all the headers during the `advertise-alive` event, I see two adverts from my local machine:

```javascript
var server = new Server()
server.addUSN('my-service-type')
server.start()

server.on('advertise-alive', function (headers) {
  console.info(headers)
})
```

Results in:

```javascript
{
  HOST: '239.255.255.250:1900',
  NT: 'my-service-type',
  NTS: 'ssdp:alive',
  USN: 'uuid:f40c2981-7329-40b7-8b04-27f187aecfb5::my-service-type',
  LOCATION: 'http://10.1.83.55:10293/upnp/desc.html',
  'CACHE-CONTROL': 'max-age=1800',
  SERVER: 'node.js/0.12.6 UPnP/1.1 node-ssdp/2.2.2'
}
{
  HOST: '239.255.255.250:1900',
  NT: 'uuid:f40c2981-7329-40b7-8b04-27f187aecfb5',
  NTS: 'ssdp:alive',
  USN: 'uuid:f40c2981-7329-40b7-8b04-27f187aecfb5',
  LOCATION: 'http://10.1.83.55:10293/upnp/desc.html',
  'CACHE-CONTROL': 'max-age=1800',
  SERVER: 'node.js/0.12.6 UPnP/1.1 node-ssdp/2.2.2'
}
```

I would expect to only see the USN I specified advertised.  I think this is because server.js [adds it's UDN to it's list of UPNs](https://github.com/diversario/node-ssdp/blob/master/lib/server.js#L28).

Was this done on purpose?  Would you be amenable to a PR that changes it to give the user a bit more control over what's advertised?

**Comment by diversario** [comment]
Looks like a bug. I can't recall why the server would need to add itself to the list of USNs. A PR would be very welcome!
