### ISSUE TITLE
Crash on empty NTS headers

### ISSUE THREAD

**Issue by mnkhouri** [diversario/node-ssdp#45]
When receiving a message with empty NTS headers, node-ssdp throws an exception because there is a toLowerCase(): `headers.NTS.toLowerCase()` at https://github.com/diversario/node-ssdp/blob/master/lib/index.js#L258

I have submitted two (almost identical PRs) that both fix this. The only practical difference between the two is that one returns early while the other lets node-ssdp fall through to the "default" case and adds more logging.

https://github.com/diversario/node-ssdp/pull/43
https://github.com/diversario/node-ssdp/pull/44

**Comment by diversario** [comment]
Published v2.6.5.
