### ISSUE TITLE
Remove `bunyan` dependency

### ISSUE THREAD

**Issue by feross** [diversario/node-ssdp#47]
Hi there! Excellent package – thanks for the good work.

We use this in [`webtorrent`](https://webtorrent.io/) and [`peerflix`](https://github.com/mafintosh/peerflix) and there's been one repeated issue that keeps coming up.

Some users don't have compiler toolchains installed on their machines, so they get huge ugly error warnings when trying to install anything that depends on `node-ssdp` since it uses `bunyan` (which has a native dependency on `dtrace-provider`).

It's nice that you've used optionalDependencies so the installation won't fail entirely, but it's still terrible UX for inexperienced users. Seeing a wall of errors makes them think that their installation has failed, even when it has not.

For this reason, I think we should aggressively avoid native dependencies wherever possible. Even more so, when the native dependencies have nothing to do with the main purpose of the package.

`bunyan` is just a logger, so it seems silly to have all of this trouble for a logging utility when we could just use one that's pure javascript and avoid the trouble all together. There are simpler, lighter weight loggers that we could use. I'm a fan of [`debug`](https://www.npmjs.com/package/debug) but anything without a native dependency is just fine. :+1: 

Another reason to get rid of `bunyan` is how much of the *production* dependency tree is devoted to it. All the packages with `**` in front of them are installed for bunyan.

```
test@1.0.0 /Users/feross/code/test
└─┬ node-ssdp@2.6.5
**  ├─┬ bunyan@1.5.1
**  │ ├─┬ dtrace-provider@0.6.0
**  │ │ └── nan@2.1.0
**  │ ├─┬ mv@2.1.1
**  │ │ ├─┬ mkdirp@0.5.1
**  │ │ │ └── minimist@0.0.8
**  │ │ ├── ncp@2.0.0
**  │ │ └─┬ rimraf@2.4.5
**  │ │   └─┬ glob@6.0.3
**  │ │     ├─┬ inflight@1.0.4
**  │ │     │ └── wrappy@1.0.1
**  │ │     ├── inherits@2.0.1
**  │ │     ├─┬ minimatch@3.0.0
**  │ │     │ └─┬ brace-expansion@1.1.2
**  │ │     │   ├── balanced-match@0.3.0
**  │ │     │   └── concat-map@0.0.1
**  │ │     ├─┬ once@1.3.3
**  │ │     │ └── wrappy@1.0.1
**  │ │     └── path-is-absolute@1.0.0
**  │ └── safe-json-stringify@1.0.3
**  ├── bunyan-pretty-colors@0.1.7
**  ├── bunyan-prettystream@0.1.3
  └── ip@1.1.0
```

An install script, native compilation, and 22 dependencies is just too high of a cost for a logging utility.

I'm happy to send a PR to use `debug` if you're interested. Cheers! :+1:

**Comment by diversario** [comment]
I agree, native dependencies can definitely be a nuisance. I'm fine with replacing `bunyan` with something else. `debug`, though – last time I tried using it didn't even support logging objects properly, I was rather disappointed with it.

I use `bunyan` quite a bit when debugging and as you can see a lot of trace/debug level logs are logging objects. If `debug` can handle that – great, but if not then we should find something that can.

**Comment by feross** [comment]
This works to log objects in `debug`:

```js
debug('this is an object: %o', obj)
```

I can send a PR so we can see if it'll do the job. If not, happy to use whatever you suggest.

**Comment by diversario** [comment]
Please do, let's figure this out.

**Comment by feross** [comment]
Just sent a PR to remove `bunyan` and used `debug` instead: https://github.com/diversario/node-ssdp/pull/52

Since `debug` is pretty barebones, I removed the various log levels. You can enable logging via an environment variable `DEBUG`. Set `DEBUG=node-ssdp*` to enable all logs. To enable only client or server logs, use `DEBUG=node-ssdp:client` or `DEBUG=node-ssdp:server` respectively.

Tests pass :+1:

**Comment by diversario** [comment]
v2.7.0 published.

Honestly, not a fan of `console.log`-style logging but at the same time – this is just a library used by other projects and I'm probably the only one who cares about logging. So `¯\_(ツ)_/¯`

Thank you for the PR! :+1: :smile:

**Comment by feross** [comment]
Thanks! :+1:

**Comment by fisch0920** [comment]
:+1:

**Comment by oeuillot** [comment]
:+1:
