### ISSUE TITLE
The configured port is not used by the client

### ISSUE THREAD

**Issue by vjrantal** [diversario/node-ssdp#50]
[This line](https://github.com/diversario/node-ssdp/blob/68bdb8883c14c9fb12039927775e0407e8cafdf8/lib/client.js#L26) starts the client always using port 0 instead of the one from the configuration.

**Comment by driskell** [comment]
I think the port in the configuration is intended to be the target SSDP port on the network, not the originating bound port. Port 0 generates a random port number that is guaranteed to not be in use already. But setting it to _ssdpPort looks like it would break my usage as I have two discovery processes running and it would mean under default config one would fail to bind.

I'll hopefully raise a PR soon to allow it to be passed in as an additional configuration value which defaults to 0, maintaining current behaviour unless it's actually set.

**Comment by diversario** [comment]
@driskell is correct. I'll leave the current behavior as-is for now.
