### ISSUE TITLE
dgram.createSocket is not function (Ionic2)

### ISSUE THREAD

**Issue by JulianGarciaCastillo** [diversario/node-ssdp#64]
Hello!
I'm getting `dgram.createSocket is not a function` using Ionic 2(cordova).
Is this not compatible with cordova ? 
Thank  you!

**Comment by diversario** [comment]
That's entirely possible. I never used cordova so I don't know what socket interface looks like there but this library was written just for node. However, if you manage to find a way to make it work in Cordova – don't hesitate to submit a pull request!
