### ISSUE TITLE
License and license headers.

### ISSUE THREAD

**Issue by bobpiece** [diversario/node-ssdp#67]
Could You add license file as a part of node-ssdp repository?
I am going to use it in my project by my organisation doesn't allow to use any library which doesn't include license file. Yes, I know that ypur README.md refers to the MIT license but it is not good enough for me.
Could you think also about adding license header to the source code files?

**Comment by diversario** [comment]
Sounds reasonable.

**Comment by diversario** [comment]
Added in `v3.0.0-beta2`.
