### ISSUE TITLE
Not getting "response" event

### ISSUE THREAD

**Issue by ChriD** [diversario/node-ssdp#72]
Hi,
I am having troubles getting the "response" event on the client
I am doing a search on the client

```
var client = new Client({customLogger: logx});
client.search('urn:schemas-upnp-org:device:MediaRenderer:1');

client.on('notify', function () {
  console.log('Got a notification.')
})

client.on('response', function inResponse() {
    console.log('response');
})

client.on('advertise-alive', function inResponse() {
    console.log('advertise-alive');
})

client.on('advertise-bye', function inResponse() {
    console.log('advertise-bye');
})

client.on('m-search', function inResponse() {
    console.log('m-search');
})
```

and the log i am getting is this one
```
SSDP listening: %o  {"address":"http://0.0.0.0:1900","interface":"192.168.56.1"}
SSDP listening: %o  {"address":"http://0.0.0.0:1900","interface":"10.0.0.4"}
Sending an M-SEARCH request  undefined
Sent M-SEARCH request: %o  {"message":"M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:device:MediaRenderer:1\r\nMAN: \"ssdp:discover\"\r\nMX: 3\r\n\r\n"}
SSDP M-SEARCH event: %o  {"ST":"urn:schemas-upnp-org:device:MediaRenderer:1","address":"10.0.0.4","port":1900}
SSDP M-SEARCH event: %o  {"ST":"urn:schemas-upnp-org:device:MediaRenderer:1","address":"10.0.0.4","port":1900}
SSDP M-SEARCH event: %o  {"ST":"upnp:rootdevice","address":"10.0.0.111","port":38182}
SSDP M-SEARCH event: %o  {"ST":"upnp:rootdevice","address":"10.0.0.111","port":38182}
SSDP M-SEARCH event: %o  {"ST":"upnp:rootdevice","address":"10.0.0.111","port":38182}
SSDP M-SEARCH event: %o  {"ST":"upnp:rootdevice","address":"10.0.0.111","port":38182}
SSDP M-SEARCH event: %o  {"ST":"ssdp:all","address":"10.0.0.111","port":53319}
SSDP M-SEARCH event: %o  {"ST":"upnp:rootdevice","address":"10.0.0.111","port":54712}
SSDP M-SEARCH event: %o  {"ST":"upnp:rootdevice","address":"10.0.0.111","port":54712}
```

So it seems that i am getting 2 Media Renderers Search events which should trigger the "response" event? But the response is nerver been called?
What i am doeing wrong? I tried several branches and the current stable package. All behave a little bit different. 

I have a Virtual Ethernet Adapter. If i am deactivating this adapter the problem persists.
Any Idea?

**Comment by diversario** [comment]
Hi Chris!

Can you tell me a little more about what you expect to see – is there a device on your network that you expect to respond to this search?

**Comment by ChriD** [comment]
Of course!
I have a HUAWAI HA35-22/AM (AV1HA35M VER.A)  (A hybrid router DSL+4G)
And i am trying to find all media renderers on the 10.0.0x network.

I'am expection to get the "response" even for the devices/services (of course only the Renderers) as given by the Intel UPNP device Spy. That should be 3 Media Renderers as marked in the screenshot
![grafik](https://cloud.githubusercontent.com/assets/2505067/23091908/99da489a-f5c0-11e6-8376-a595c2e8ace9.png)

Bu as you can see i only get 2 MediaRenderers Search Events and for those 2 the "response" event is not getting called
![grafik](https://cloud.githubusercontent.com/assets/2505067/23091927/d33048ba-f5c0-11e6-8986-e6c66d7201c2.png)

After a while (~20 seconds) i get a lots of advertise alive events very fast
![grafik](https://cloud.githubusercontent.com/assets/2505067/23091943/254337e8-f5c1-11e6-8c58-faa2406523ba.png)

When i turn on a new Media Renderer, it will not be recognized either but i get again a lot of advertise alive events (but in this case immediately when turning on the renderer) But i never get any response event as i should get like in the client example.

I have tried to disable the firewall and to start node with admin rights. The same behaviour.
But it should not be a problem with the firewall or admin rights at all because the Intel Device Spy and the openHome UPNP Stack can find the devices.

I have also tried to disable the VirtualBox Network Adapter with the same results

I'm not sure whats the problem here..

**Comment by diversario** [comment]
This is all great stuff, @ChriD, thank you for going to such lengths to investigate! 👏

To test binding to `10.0.0.4` you'll need to pass `reuseAddr` when creating a socket, like so https://github.com/diversario/node-ssdp/blob/master/lib/index.js#L158

I find it interesting that disabling Window's SSDP service fixes the problem. As far as I know, multicast messages are multiplexed to all listeners bound to a socket, so even if there's already another service listening it shouldn't interfere with others.

One thing to try is `explicitSocketBind: true` constructor option:
```javascript
const client = new Client({customLogger: logx, explicitSocketBind: true});
```
This will bind sockets to a specific address instead of `0.0.0.0`. Please try this and let me know the results!

**Comment by ChriD** [comment]
Thanks for the anser!

The 'explicitSocketBind' unfortunetaly does not change anything. I have tried this before too.
When i try this one for testing.
`this.ssdpClient = new SsdpClient({explicitSocketBind: true, reuseAddr: true, ssdpIp: '10.0.0.4'});`
i get an exception
` addMembership is not defined` 

I will investigate further. Thank you for your help, i think we may close the issue for now. Maybe I'll come back later if i need more help or if i found a solution without disableing the SSDPSRV

**Comment by ChriD** [comment]
I investigated further and its a little bit crazy...
The upnp lib i am using in c++ binds the ssdp ip directly and gets the SSDP events very smoothly. The node binds on 0.0.0.0 and gets the events delayed.

iIt's the same if i am subscribing to device services. In node they are delayd. Sometimes a view seconds and sometimes it goes up to 60 seconds. I think i have to dig deeper in the nodeJs server/client stuff

**Comment by diversario** [comment]
Hmm, you're saying that it works if you bind your listener to a specific IP address?

**Comment by diversario** [comment]
I think you might've found a bug. Currently, when sockets are bound they're bound to port `1900` – https://github.com/diversario/node-ssdp/blob/master/lib/index.js#L247-L249 – I think that might be wrong and they should be instead bound to a random port (`0`).

Could you try something? Could you modify those lines I linked to to be
```
      socket.bind(0, iface, next)
    } else {
      socket.bind(next) // socket binds on 0.0.0.0
```

**Comment by ChriD** [comment]
> Could you try something? Could you modify those lines I linked to to be

Looks way better! 
Even with activated Windows SSDP service!
But in fact one media server is not always found.. I have to check this but this should be another problem

**Comment by diversario** [comment]
Oh, nice! Sounds like I should be making a bugfix release.

**Comment by diversario** [comment]
@ChriD v3.2.0 is out 🙌

**Comment by ChriD** [comment]
Thanks you! very nice!

**Comment by diversario** [comment]
No, thank you for doing all this fantastic investigative work 😄! Very much appreciated!

**Comment by brandonros** [comment]
![image](https://user-images.githubusercontent.com/8949910/142778189-2c9073cb-6d88-4b58-80b8-909976f3668b.png)

Sorry to dig up an old thread but I'd love some help. I have an ARRIS TG9452 router that claims to support UPnP (and have it enabled, as per the screenshot) yet I can't get a result/response no matter what I bind address wise. Any tips?
