### ISSUE TITLE
M-SEARCH is sent each adapter which has an ip?

### ISSUE THREAD

**Issue by ChriD** [diversario/node-ssdp#73]
Hi,

When checking the SSDP messages when using the lib i am seeing that the M-SEARCH is done each adapter which has an IP? But the M-SEARCHES are completely the same. Why is this necessary? This will result in getting multiple responses for the same devices. Is this a Bug or is this as by design?
![grafik](https://cloud.githubusercontent.com/assets/2505067/23093284/10a9d882-f5df-11e6-8e3e-147acdb4f615.png)

When i am deactivating the second adapter, only one M-SEARCH is beeing created and the devices only response once, what would be ok.

**Comment by diversario** [comment]
Older version of this lib was using the first NIC it would find. But, that wouldn't always work because sometimes the first adapter could be one that doesn't actually have real connectivity. So, now, it uses all interfaces.

**Comment by ChriD** [comment]
Okay, so it is by design
