### ISSUE TITLE
Dependency on dgram?

### ISSUE THREAD

**Issue by jsvb1977** [diversario/node-ssdp#88]
Looks like the dependency on dgram is causing an issue when integrating into my Angular2+ project. Unfortunately, dgram on npm no longer exists.

**Comment by diversario** [comment]
`dgram` is node's internal module – https://nodejs.org/dist/latest-v8.x/docs/api/dgram.html

I think people who wanted to use this module in a browser context used something like `browserify` (but I'm not really sure).

**Comment by jsvb1977** [comment]
Yeah -- ok. I'm still learning the separation of browser -vs- server in regards to node server applications compared to a browser context. See, I thought that webpack (or browserify) would package everything up and make it available in the browser -- but I'm not sure yet -- or, at least, I'm not sure how to make that happen.

**Comment by diversario** [comment]
Honestly, I don't do any JS in the browser so I can't tell you what to use.
